FROM node:18.14.2 AS builder
WORKDIR /usr/src/app
COPY package*.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn run build:custom

FROM node:18.14.2 as runner
WORKDIR /usr/src/app
COPY package*.json yarn.lock ./
RUN yarn
COPY . .
COPY --from=builder /usr/src/app/dist ./dist
WORKDIR /usr/src/app/dist
CMD ["node", "server.js"]
