name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  cd:
    strategy:
      matrix:
        target_service: [api]
        include:
          - target_service: api
            helm_target: fvm-explorer-api
            helm_image_tag_env_var_name: FVM_EXPLORER_API_IMAGE_TAG
            gcr_image_path: "fvm-explorer/fvm-explorer-api"
    name: Build FVM Explorer API
    uses: ./.github/workflows/_deploy_gke_service.yml
    with:
      target_service: ${{ matrix.target_service }}
      helm_target: ${{ matrix.helm_target }}
      helm_image_tag_env_var_name: ${{ matrix.helm_image_tag_env_var_name }}
      environment: production
      helm_env: production
      runs_on_labels: '["self-hosted", "production-runner"]'
      gcr_image_path: ${{ matrix.gcr_image_path }}
      docker_file: docker/Dockerfile.server
    secrets:
      gcr_service_account_id: ${{ secrets.GCR_SERVICE_ACCOUNT_ID }}
      gke_service_account_id: ${{ secrets.GKE_SERVICE_ACCOUNT_ID_PRODUCTION }}
      gcr_region: ${{ secrets.GCR_REGION }}
      gke_region: ${{ secrets.GKE_REGION }}
      gc_project_id: ${{ secrets.GC_PROJECT_ID_PRODUCTION }}
      gcr_project_id: ${{ secrets.GCR_PROJECT_ID }}
      iam_workload_identity_pool_provider_id: ${{ secrets.IAM_GKE_WORKLOAD_IDENTITY_POOL_PROVIDER_ID }}
      deploy_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      gke_cluster_name: ${{ secrets.CLUSTER_NAME_PRODUCTION }}
      vault_connection_string: ${{ secrets.VAULT_CONNECTION_STRING_PRODUCTION }}
      vault_token: ${{ secrets.VAULT_TOKEN_PRODUCTION }}
