name: deploy

on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      env_file_encoded_content:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: ${{ inputs.project_path }}
    steps:
      - uses: actions/checkout@v

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure dir exists and is in clean state
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ${{ inputs.project_path }}
            cd ${{ inputs.project_path }}
            git checkout 2>/dev/null || true

      - name: Copy the code with rsync
        run: rsync -avz --progress . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$PROJECT_PATH

      - name: Build and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ inputs.project_path }}
            echo -n ${{ secrets.env_file_encoded_content }} | base64 -d > .env
            source .env
            yarn build:custom && yarn start:custom
